import assert from 'node:assert/strict';
import {headings,evolution} from './dist/engine.js';
import {loadClinicalState,CLINICAL_KEY} from './dist/storage.js';
const p={HDA:'admissão original',events:[{at:'2026-09-08T00:00:00Z',text:'nova informação'}]};
const t=evolution(p);
assert.deepEqual(headings,['QP','HDA','HPP','EXAME','EXAMES','HD','CONDUTA']);
assert(t.includes('# HDA\nADMISSÃO ORIGINAL'));
assert(t.includes('# EM TEMPO'));
assert(t.includes('# HPP\nNA'));
assert.equal(p.HDA,'admissão original');
const legacy=JSON.stringify({patients:[p],shifts:[{id:'legacy'}],audit:[]});
const records=new Map([['zera-v2',legacy]]);
const storage={getItem:key=>records.get(key)??null};
assert.deepEqual(loadClinicalState(storage),{patients:[p]});
assert.equal(records.get('zera-v2'),legacy);
records.set(CLINICAL_KEY,JSON.stringify({patients:[]}));
assert.deepEqual(loadClinicalState(storage),{patients:[]});
records.set(CLINICAL_KEY,'invalid');
assert.throws(()=>loadClinicalState(storage));
records.clear();
assert.deepEqual(loadClinicalState(storage),{patients:[]});
console.log('10 verificações aprovadas: documentação, separação clínica e preservação dos dados legados.');
